analyzer:
  errors:
    must_be_immutable: ignore ignore ignore ignore ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    unnecessary_null_comparison: ignore
inc ignorelude: package:flutter_lints/flutter.yaml
