name: fixnshop_admin
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  barcode_scan2: ^4.3.0
  barcode_widget: ^2.0.4
  cached_network_image: ^3.3.1
  camera: ^0.10.5+9
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.3
  dotted_line: ^3.2.2
  dropdown_search: ^6.0.0
  esc_pos_utils: ^1.1.0
  flutter:
    sdk: flutter
  flutter_barcode_listener: ^0.1.4
  flutter_bluetooth_serial: ^0.4.0
  flutter_pdfview: ^1.3.3
  font_awesome_flutter: ^10.7.0
  get: ^4.6.5
  google_nav_bar: ^5.0.6
  http: ^1.1.0
  image_cropper: ^6.0.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  path_provider: ^2.1.4
  pdf: ^3.8.4
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/touch.png